config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  # ActiveAdmin.routes(self)
#   namespace :admin do
#     resources :users
# resources :companies
# resources :company_documents
# resources :company_photos
# resources :faqs
# resources :investments
# resources :investment_documents
# resources :investment_photos
# resources :investment_videos
# resources :legals
# resources :questionnaires
# resources :reports
# resources :report_authors
# resources :report_categories
# resources :staffs
# resources :updates
# resources :user_documents
# resources :user_photos
# resources :user_videos
# resources :videos

  #   root to: "users#index"
  # end

  get 'public/index'

  get 'public/blog'

  get 'public/contact_us'

  get 'public/about'

  get 'public/team'

  get 'public/faq'

  get 'public/legal'

  get 'public/impact_investing'

  get 'pages/index'

  get 'pages/blog'

  get 'pages/contact_us'

  get 'pages/about'

  get 'pages/team'

  get 'pages/faq'

  get 'pages/legal'

  get 'pages/impact_investing'

  resources :legals
  resources :faqs


  # ActiveAdmin.routes(self)
  # resources :questionnaires, only: [:index] do
  #   get :change_status, on: :member
  # end

  resources :companies do
    get :crop
    get :get_cities_by_country_code, on: :collection
    resources :questionnaires do
      get :change_status, on: :member
    end
  end

  root to: 'visitors#index'

  resources :investments do
    get :crop
  end
  # resources :companies do
    
  # end
  


  resources :terms


  resources :after_signup
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/crop" => "users#crop"
  resources :users do
    get :get_cities_by_country_code, on: :collection
    
    collection do
      get :filter_courses  
    end
  end

  resources :reports
  
  
  get "welcome" => "after_signup#welcome", as: :user_welcome
  get "location" => "after_signup#location", as: :user_location
  get "setup" => "after_signup#setup", as: :user_setup
  get "resume" => "after_signup#resume", as: :user_resume
  get '/faq', to: 'investments#faq'
  get '/privacy_policy', to: 'public#privacy_policy'

  end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

layout :layout_by_resource

	def index
      if user_signed_in?
        render :file => "app/views/public/index"
      else
        render "index"
      end
    end 
       
    def layout_by_resource
      if user_signed_in?
        "application"
      else
        "minimal"
      end
    end
end

app/views/visitors/_featured_investments.html.erb
<div class="container-row bgcolor-white">
  <div class="container p-y-lg">
  </div>
</div>  

app/views/visitors/_hero_header.html.erb
<style type="text/css">
.whatever{ 
background: url(<%= image_url("public-bg.jpg")%>) no-repeat center center fixed; 
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;
}
</style>

<div class="container p-y-lg mobile-center" style="padding: 50px 0 100px 0; height: 800px;">
  <h1 class="cover-heading hero m-n">Invest in your world.</h1>

  <div class="row">
    <div class="col-md-7 col-sm-12">
      <p class="lead" style="font-size: 30px; line-height: 1.2;">
      	Earn competitive returns while driving meaningful impact in the last economic frontiers.
      </p>
      <br/>
      <p class="lead bold" style="font-size: 20px; line-height: 1.2;">
        VestedWorld is an emerging market venture capital platform.
      </p>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <div class="row">
        <div class="col-sm-6">
          <%= link_to "Join our Community", new_user_registration_path, class: "btn btn-rounded btn-lg btn-block pull-right text-white" %>
        </div>
        <div class="col-sm-6">
          <%= link_to "Apply for Funding", new_user_session_path, class: "btn btn-rounded btn-block btn-default btn-lg pull-right", target: "_blank", style: "background: transparent; " %>
        </div>
      </div>
    </div>
  </div>
</div>


<%#= link_to "What is Impact Investing ?", "http://vestedworld.com/about-us/", class: "btn btn-rounded btn-block btn-default pull-right", target: "_blank", style: "background: transparent; " %>

app/views/visitors/_top_nav.html.erb
<div class="container p-y-lg">
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-left">
        <h3 class="m-t-0 font-logo">
          <%= image_tag("white-mark.png", style: "width: 70px;") %>
          <%= image_tag("white-type.png", style: "width: 150px; margin-left: -25px;") %>
        </h3>
      </div>
      <div class="pull-right">
        <nav>
          <ul class="nav ul-inline bold m-y">
            <li>
              <%=link_to "Investments", investments_path %>
            </li>
            <li>
              <%=link_to "Companies", companies_path %>
            </li>
            <li><%=link_to "VestedWorld Home", "http://vestedworld.com", target: "_blank", rel: "nofollow"%></li>
            <li><%=link_to "FAQ", "http://vestedworld.com/resources/faqs/", target: "_blank", rel: "nofollow"%></li>
            <li>
              <%= link_to 'Account Login', new_user_session_path, class: "btn btn-rounded btn-block btn-default tb btn-sm p-x bold" %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<style type="text/css">
.whatever{ 
background: url(<%= image_url("public-bg.jpg")%>) no-repeat center center fixed; 
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;
}
</style>
<div class="container-row">
  <div class="row">
    <div class="col-md-12">
      
      <!-- Top Nav -->
      <%= render 'visitors/top_nav' %>

      <!-- Masthead hero -->
      <%= render 'visitors/hero_header' %>

      <!-- Featured -->
      <%#= render 'visitors/featured_investments' %>

    </div>
  </div>
</div>