config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  # ActiveAdmin.routes(self)
#   namespace :admin do
#     resources :users
# resources :companies
# resources :company_documents
# resources :company_photos
# resources :faqs
# resources :investments
# resources :investment_documents
# resources :investment_photos
# resources :investment_videos
# resources :legals
# resources :questionnaires
# resources :reports
# resources :report_authors
# resources :report_categories
# resources :staffs
# resources :updates
# resources :user_documents
# resources :user_photos
# resources :user_videos
# resources :videos

  #   root to: "users#index"
  # end

  get 'public/index'

  get 'public/blog'

  get 'public/contact_us'

  get 'public/about'

  get 'public/team'

  get 'public/faq'

  get 'public/legal'

  get 'public/impact_investing'

  get 'pages/index'

  get 'pages/blog'

  get 'pages/contact_us'

  get 'pages/about'

  get 'pages/team'

  get 'pages/faq'

  get 'pages/legal'

  get 'pages/impact_investing'

  resources :legals
  resources :faqs


  # ActiveAdmin.routes(self)
  # resources :questionnaires, only: [:index] do
  #   get :change_status, on: :member
  # end

  resources :companies do
    get :crop
    get :get_cities_by_country_code, on: :collection
    resources :questionnaires do
      get :change_status, on: :member
    end
  end

  root to: 'visitors#index'

  resources :investments do
    get :crop
  end
  # resources :companies do
    
  # end
  


  resources :terms


  resources :after_signup
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/crop" => "users#crop"
  resources :users do
    get :get_cities_by_country_code, on: :collection
    
    collection do
      get :filter_courses  
    end
  end

  resources :reports
  
  
  get "welcome" => "after_signup#welcome", as: :user_welcome
  get "location" => "after_signup#location", as: :user_location
  get "setup" => "after_signup#setup", as: :user_setup
  get "resume" => "after_signup#resume", as: :user_resume
  get '/faq', to: 'investments#faq'
  get '/privacy_policy', to: 'public#privacy_policy'

  end

app/models/investment.rb
class Investment < ActiveRecord::Base
  self.inheritance_column = :ruby_type

  validates :company_id, :presence => true

 	enum type: [:debt, :equity, :convertible]
  belongs_to :company

  belongs_to :investor, :class_name => "User", :foreign_key => "investor_id"

  has_many :updates, as: :updateable, :dependent => :destroy
  accepts_nested_attributes_for :updates, allow_destroy: true, :reject_if => Proc.new { |update| update['title'].blank? }

  has_many :investment_documents, :dependent => :destroy
  accepts_nested_attributes_for :investment_documents, reject_if: :all_blank, allow_destroy: true

  has_many :investment_photos, :dependent => :destroy
  accepts_nested_attributes_for :investment_photos, reject_if: :all_blank, allow_destroy: true

  has_many :investment_videos, :dependent => :destroy
  accepts_nested_attributes_for :investment_videos, allow_destroy: true, :reject_if => Proc.new { |investment_video| investment_video['link'].blank?  }

  has_one :term_sheet, :dependent => :destroy 
  accepts_nested_attributes_for :term_sheet, reject_if: :all_blank, allow_destroy: true
  has_many :users, :class_name => "User", :through => :staffs, :source => :user
  has_many :staffs, :dependent => :destroy
  
  mount_uploader :logo, PhotoUploader
  mount_uploader :background_image, PhotoUploader
  crop_uploaded :background_image


  after_create :send_investment_created_email

  private
  def send_investment_created_email
    InvestmentMailer.investment_created_mail(self).deliver
  end



end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: [:show, :edit, :update, :destroy]

  # GET /investments
  # GET /investments.json
  def index
    @users = User.all
    @grouped_investments = Investment.group(:location).count
    @investments = Investment.order(:title => :asc)
    @investments = @investments.where("LOWER(title)=?", params[:q].downcase) if params[:q].present?


    render layout: "browse"
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
     if  user_signed_in?
      response.headers.delete "X-Frame-Options"
    else
      redirect_to root_path
    end
  end

  # GET /investments/new
  def new
    if current_user.admin?
      @investment = Investment.new
      @investment.build_term_sheet
    else
      flash[:danger] = "You are not unauthorized access this."
      redirect_to root_url
    end

  end

  # GET /investments/1/edit
  def edit
    if current_user && (@investment.investor_id.eql?(current_user.id) || current_user.admin?)
    else
      respond_to do |format|
        flash[:danger] = 'Unauthorized user!'
        format.html { redirect_to root_path }
      end
    end
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      @investment.investor = current_user
      if @investment.save
        update_staffs
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        flash[:danger] = @investment.errors.full_messages.join(', ')
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        update_staffs
        if investment_params[:background_image].present?
          redirect_to investment_crop_url(@investment) and return
        else
          format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
          format.json { render :show, status: :ok, location: @investment }
        end
      else
        flash[:danger] = @investment.errors.full_messages.join(', ')
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    respond_to do |format|
      if current_user && (@investment.investor_id.eql?(current_user.id) || current_user.admin?)
        @investment.destroy  
        format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
        format.json { head :no_content }
      else
        flash[:danger] = 'Unauthorized user!'
        format.html { redirect_to root_path }
      end
    end
  end

  def crop
    @investment = Investment.find(params[:investment_id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit(:title, :size, :description, :type, :revenue_share, :start_date, :logo,:end_date, :company_id, :industry, :stage, :staff_users, :location, :expected_return, :background_image, :background_image_crop_x, :background_image_crop_y, :background_image_crop_w, :background_image_crop_h, :highlights_1,:highlights_2, :highlights_3, :highlights_4, :highlights_5, :highlights_6, :highlights_7, :highlights_8, :highlights_9, :highlights_10, :overview_1, :overview_2, :overview_3, :problem_bullet_1, :problem_bullet_2, :problem_bullet_3, :problem_bullet_4, :problem_bullet_5,:solution_bullet_1, :solution_bullet_2, :solution_bullet_3, :solution_bullet_4, :solution_bullet_5,:updates_attributes => [:id, :title, :brief_description, :detailed_description, :_destroy], :user_ids => [], :investment_photos_attributes => [:id, :investment_image,  :_destroy], :investment_documents_attributes => [:id, :document, :investment_id, :_destroy], :investment_videos_attributes => [:id, :title, :link, :description, :investment_id, :_destroy],:term_sheet_attributes => [:id, :investment_id, :description, :security, :automatic_conversion, :interest_rate, :interest_payments, :maturity_date, :conversion_discount, :conversion_cap, :optional_conversion, :redemption_option, :min_investment_for_vestedAngels, :min_Raise_through_vestedAngels, :max_raise_through_vestedAngels, :maximum_fund_investors, :management_fee, :carried_interest, :administrative_cost, :target_closing_date, :other])
    end

    def update_staffs
      if params["staff_users"].present?
        @investment.staffs.destroy_all
        params["staff_users"].each do |role,user_ids|
          user_ids.reject!{|id| id.blank? }
          user_ids.each do |user_id|
            @investment.staffs.create(:user_id => user_id, :role => role)
          end
        end
      end

    end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
	
	def term_sheet
		@investment.term_sheet
	end
end

app/views/investments/edit/_advisors.html.erb
<section id="nav-advisors">
  <h6>Notable Advisors</h6>

  <h5 class="bold m-b-0">Add Advisors</h5>
  <p class="text-muted">Please select advisors that should be associated with this investment.</u></b></p>
  <%= f.collection_select :user_ids, User.all, :id, :email, {:selected => @investment.staffs.send("Advisor").map(&:user_id) }, {:name => "staff_users[#{"Advisor"}][]", :multiple => true, class: "select2"} %>
  <br/>
  

</section>

app/views/investments/edit/_data_room.html.erb
<section>
  <h6>Data Room</h6>

  <h4>Getting in touch.</h4>
  <p>Don't worry. We won't make any of your more sensitive contact information publicly available and we will only contact you upon request. </u></b></p>
  <br/>       


  <!-- DEAL DATA Room -->
  <div id="nav-dataroom">
    <h4 class="bold">Deal Data Room</h4>
    <div id="deal_data_room">
      <div class="row">
        <div class="col-sm-12">             
        </div>
      </div>
    </div>
  </div>

</section>

app/views/investments/edit/_header.html.erb
<% header_background_image_url = f.object.background_image.present? ? f.object.background_image : "http://vestedworld.com/app/uploads/2016/03/3-1024x529.jpg"  %>


<div class="profile-header-photo gradient reduced-height" style="background: url(<%= header_background_image_url %>);">
    <div class="profile-header-photo-in">
      <div class="tbl-cell">
        <div class="info-block">
          <div class="container">
            <div class="row">
              <div class="col-lg-8 col-lg-offset-4">
                <div class="tbl info-tbl">
                  <div class="tbl-row">
                    <div class="tbl-cell">
                      <h2><%= @investment.title %></h2>
                      <h4>
                        <span class="text-warning">
                          <%= number_to_currency(@investment.size) %>
                        </span>
                        <span class="text-muted m-l m-r">|</span>
                        <small><%= @investment.type %></small>
                        <span class="text-muted m-l m-r">|</span>
                        <small><%= @investment.stage %></small>
                      </h4>
                      
                    </div>
                    <div class="tbl-cell tbl-cell-stat">
                      <div class="inline-block">
                        <!-- <p class="title">2</p>
                        <p>Videos</p> -->
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if current_user && (@investment.investor_id.eql?(current_user.id) || current_user.admin?) %>
      <%= link_to investment_path(@investment), class: "change-cover m-a-lg" do %>
        View Profile
      <% end %>
    <% end %>
  </div>

app/views/investments/edit/_highlights.html.erb
<section id="nav-highlights">
  <h6>HIGHLIGHTS</h6>

  <h5 class="m-b-0">Investment Highlights</h5>
  <p class="text-muted">Please highlight why this an attractive investment.</u></b></p>
  <br/>       

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.text_field :highlights_1 , class: "form-control", placeholder: "Highlight #1" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_2 , class: "form-control", placeholder: "Highlight #2" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_3 , class: "form-control", placeholder: "Highlight #3" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_4 , class: "form-control", placeholder: "Highlight #4" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_5 , class: "form-control", placeholder: "Highlight #5" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.text_field :highlights_6 , class: "form-control", placeholder: "Highlight #6" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_7 , class: "form-control", placeholder: "Highlight #7" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_8 , class: "form-control", placeholder: "Highlight #8" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_9 , class: "form-control", placeholder: "Highlight #9" %>
      </div>
      <div class="form-group">
        <%= f.text_field :highlights_10 , class: "form-control", placeholder: "Highlight #10" %>
      </div>
    </div>
  </div>
</section>

app/views/investments/edit/_impact.html.erb
<section id="impact">
  <h6>economic, social and environmental impact</h6>
  

   <div class="row text-center">
    <div class="col-md-4">
      <h6>What we Like the Opportunity</h6>
      <%= image_tag("screenshots/screen-1.png", style: "width: 80%;") %>
    </div>
    <div class="col-md-4">
      <h6>Social and Environmental Impact</h6>
      <%= image_tag("screenshots/screen-2.png", style: "width: 80%;") %>
    </div>
    <div class="col-md-4">
      <h6>Market Overview</h6>
      <%= image_tag("screenshots/screen-3.png", style: "width: 80%;") %>
    </div>
  </div>
</section>

app/views/investments/edit/_intro.html.erb
<section id="nav-intro">
	<h6>1. INTRODUCTION</H6>
	<h5 class="bold m-b-0">General Investment Information</h5>
  <p class="text-muted">Please complete a term sheet.</u></b></p>
  <br/>
  <div class="form-group">
    <label class="form-label">Select Company<small> Please selete the company this investment is associated with.</small></label>
    <%= f.collection_select :company_id, Company.all, :id, :name, :include_blank => "Please Select",  class: "form-control width-100p" %>
  </div>
  <br/>               
	<div class="form-group">
  	<label class="form-label">Title<small> Describes the financing.</small></label>
	  <%= f.text_field :title, class: "form-control", placeholder: "Investment Title" %>
	</div>
	<br/>
	<div class="form-group">
	  <label class="form-label">
	    Pitch Teaser<small> Very brief description.</small>
	  </label>
	  <%= f.text_area :description , class: "form-control" , rows: "5", placeholder: "Teaser Description" %>
	</div>
	<div class="form-group">
	  <label class="form-label">
	    Bachground Header
	  </label>
	  <% if f.object.background_image.present? %>
	    <%= image_tag f.object.background_image.url,:class => "image-responsive p-a-0", :id => "bg_output" %>
	  <% else %>
	    <%= image_tag("bg.jpeg", :class => "image-responsive p-a-0", :id => "output")%>
	  <% end %>  
	  <%= f.file_field :background_image , class: "form-control", :onchange=>"loadFile(event)"%>
	</div>
</section>

<script type="text/javascript">
  var loadFile = function(event) {
    var bg_output = document.getElementById('bg_output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

app/views/investments/edit/_investment_overview.html.erb
<section>
  <h6>Investment Overview</h6>
  <!-- Term Sheet -->
  <div id="nav-terms">
    <h5 class="bold m-b-0">Term Sheet</h5>
    <p class="text-muted">Please complete a term sheet.</u></b></p>
    <div id="term_sheet">
      <div class="row">
        <div class="col-sm-12"> 
          <%= f.fields_for :term_sheet do |term| %>
            <%= render 'investments/term_sheet', term:term %>
          <% end %>                
        </div>
      </div>        
    </div>
  </div>
</section>

app/views/investments/edit/_investors.html.erb
<section id="nav-investors">
  <h6>VestedAngels and Select Investors</h6>

  <h5 class="bold m-b-0">Add Investors</h5>
  <p class="text-muted">Please select investors that should be associated with this investment.</u></b></p>
  <%= f.collection_select :user_ids, User.all, :id, :email, {:selected => @investment.staffs.send("Investor").map(&:user_id) }, {:name => "staff_users[#{"Investor"}][]", :multiple => true, class: "select2"} %>
  <br/>
  
  </section>

app/views/investments/edit/_legal_notices.html.erb
<div id="nav-notices">
	<h5 class="bold m-b-0">Investment Legal Notices</h5>
  <p class="text-muted">Copy and paste legal or confidentality information here. complete a term sheet.</u></b></p>
  <br/>
	<label class="form-label">Legal Notices <small>The company's legal notices.</small></label>
	<textarea class="form-control" rows="12" placeholder="<%=LegalNotice.first.try(:investment_notice)%>"></textarea>
</div>

app/views/investments/edit/_media.html.erb
<section>
  <h6>MEDIA</h6>

  <!-- DOCUMENTS -->
  <section id="nav-documents">
    <div class="form-group">
      <label class="form-label">Documents</label>
      <div id="investment_documents">
        <div class="row">
          <div class="col-sm-12">
            <div id="company_documents">
               <table class="table">
                <thead>
                  <th>Title</th>
                  <th>Documents</th>
                  <th>File</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <%= f.fields_for :investment_documents do |investment_document_form| %>
                    <%= render 'investments/investment_document_fields', f: investment_document_form %>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <hr/>
        <div class="links">
          <%= link_to_add_association f, :investment_documents, class: "btn btn-primary btn-sm" do %>
            Add New
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <br/><br/>


  <!-- PHOTOS -->
  <section id="nav-media">
    <div class="form-group">
      <label class="form-label">Photos</label>
      <div id="investment_photos">
        <div class="row">
          <div class="col-sm-12">
             <table class="table">
              <thead>
                <th>Title</th>
                <th>Documents</th>
                <th>File</th>
                <th>Actions</th>
              </thead>
              <tbody>
                <%= f.fields_for :investment_photos do |investment_photo_form| %>
                  <%= render 'investments/investment_photo_fields', f: investment_photo_form %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <hr/>
        <div class="links">
          <%= link_to_add_association 'Add Photo', f, :investment_photos, class: "btn btn-sm" %>
        </div>
      </div>
    </div>
  </section>
  

  <br/><br/>

  <!-- VIDEO -->
  <div class="form-group">
    <label class="form-label">Videos</label>
    <div id="investment_video">
      <div class="row">
        <div class="col-sm-12">
          <div id="videos">
            <%= f.fields_for :investment_videos do |video_form| %>
              <%= render 'investments/investment_video_fields', f: video_form %>
            <% end %>
          </div>
        </div>
      </div>
      <hr/>
      <div class="links">
        <%= link_to_add_association 'Add Video', f, :investment_videos, class: "btn btn-sm" %>
      </div>
    </div>
  </div>
</section>

app/views/investments/edit/_opportunity.html.erb
<section>
  <h6 id="nav-overview">the opportunity</h6>

  <article>  
    <h5 class="bold m-b-0">Business Overview</h5>
    <p class="text-muted">Please provide a complete but concise overview of the business opportunity</u></b></p>
  
    <div class="form-group">
      <%= f.text_area :overview_1 , class: "form-control", placeholder: "" %>
    </div>

    <div class="form-group">
      <%= f.text_area :overview_2 , class: "form-control", placeholder: "" %>
    </div>

    <div class="form-group">
      <%= f.text_area :overview_3 , class: "form-control", placeholder: "" %>
    </div>
  </article>
  
  <p id="nav-problem"></p>
  <article>
    <h5 class="bold m-b-0">Problem Statement</h5>
    <p class="text-muted">Please describe the market problem that you are solving</u></b></p>
    <div class="form-group">
      <%= f.text_area :problem_bullet_1 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :problem_bullet_2 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :problem_bullet_3 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :problem_bullet_4 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :problem_bullet_5 , class: "form-control", placeholder: "" %>
    </div>  
  </article>

  <p id="nav-solution"></p>
  <article>
    <h5 class="bold m-b-0">Company Solution</h5>
    <p class="text-muted">Please describe the company's solution to the problem statement.</u></b></p>
    <div class="form-group">
      <%= f.text_area :solution_bullet_1 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :solution_bullet_2 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :solution_bullet_3 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :solution_bullet_4 , class: "form-control", placeholder: "" %>
    </div>      
    <div class="form-group">
      <%= f.text_area :solution_bullet_5 , class: "form-control", placeholder: "" %>
    </div>  
  </article>

</seciton>

app/views/investments/edit/_team.html.erb
<section id="nav-founders">
  <h6>THE FOUNDING TEAM</h6>

  <h5 class="bold m-b-0">Add Corporate Team</h5>  
   <p class="text-muted">Please add corporate team members that should be associated with this investment.</u></b></p>
   <%= f.collection_select :user_ids, User.all, :id, :email, {:selected => @investment.staffs.send("Founders").map(&:user_id) }, {:name => "staff_users[#{"Founders"}][]", :multiple => true, class: "select2"} %>

</section>

app/views/investments/edit/_terms.html.erb
<section id="terms">
  <h6>Investment Terms</h6>

  <h5>Investment Term Sheet</h5>
  <p class="text-muted">
    [term sheet notice]
  </p>


  <h3></h3>
  <table class="table table-striped">
    <thead>
      <th width="35%">Term</th>
      <th>Description</th>
      </thead>
    <tbody>
      <tr>
        <td>Security:</td>
        <td>Convertible Note</td>
      </tr>
      <tr>
        <td>Automatic Conversion:</td>
        <td> Qualified Financing of $1,000,000+</td>
      </tr>
      <tr>
        <td>Interest Rate:</td>
        <td>5% per annum (7% post-maturity)</td>
      </tr>
      <tr>
        <td>Interest Payments:</td>
        <td>Accrues to principle</td>
      </tr>
      <tr>
        <td>Maturity Date:</td>
        <td>June 14, 2018</td>
      </tr>
      <tr>
        <td>Conversion Discount:</td>
        <td>20%</td>
      </tr>

      <tr>
        <td>Conversion Cap:</td>
        <td>$4,000,000</td>
      </tr>
      <tr>
        <td>Optional Conversion:</td>
        <td>Maturity, Election</td>
      </tr>
      <tr>
        <td>Redemption Option:</td>
        <td>None</td>
      </tr>
      <tr>
        <td>Other:</td>
        <td>Converts into Preferred Stock on the same terms as other purchasers; Conversion discount shall not exceed 30% under Conversion Cap Fund Terms
        </td>
      </tr>
      <tr>
        <td>Min. Investment for VestedAngels:</td>
        <td>$1,00011
        </td>
      </tr>
      <tr>
        <td>Min. Raise through VestedAngels:</td>
        <td>$10,000
        </td>
      </tr>
      <tr>
        <td>Max Raise through VestedAngels:</td>
        <td>$135,000
        </td>
      </tr>
      <tr>
        <td>Maximum Fund Investors:</td>
        <td>45
        </td>
      </tr>
      <tr>
        <td>Management Fee:</td>
        <td>45
        </td>
      </tr>
      <tr>
        <td>Maximum Fund Investors:</td>
        <td>2.5% per year12</td>
      </tr>
      <tr>
        <td>Carried Interest:</td>
        <td>20%13</td>
      </tr>
      <tr>
        <td>Administrative Cost:</td>
        <td>Pro-rata share of actual expenses incurred14</td>
      </tr>
      <tr>
        <td>Target Closing Date:</td>
        <td>September 9, 2016</td>
      </tr>
    </tbody>
    <tfooter></tfooter> 
  </table>
</section>