config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  # ActiveAdmin.routes(self)
#   namespace :admin do
#     resources :users
# resources :companies
# resources :company_documents
# resources :company_photos
# resources :faqs
# resources :investments
# resources :investment_documents
# resources :investment_photos
# resources :investment_videos
# resources :legals
# resources :questionnaires
# resources :reports
# resources :report_authors
# resources :report_categories
# resources :staffs
# resources :updates
# resources :user_documents
# resources :user_photos
# resources :user_videos
# resources :videos

  #   root to: "users#index"
  # end

  get 'public/index'

  get 'public/blog'

  get 'public/contact_us'

  get 'public/about'

  get 'public/team'

  get 'public/faq'

  get 'public/legal'

  get 'public/impact_investing'

  get 'pages/index'

  get 'pages/blog'

  get 'pages/contact_us'

  get 'pages/about'

  get 'pages/team'

  get 'pages/faq'

  get 'pages/legal'

  get 'pages/impact_investing'

  resources :legals
  resources :faqs


  # ActiveAdmin.routes(self)
  # resources :questionnaires, only: [:index] do
  #   get :change_status, on: :member
  # end

  resources :companies do
    get :crop
    get :get_cities_by_country_code, on: :collection
    resources :questionnaires do
      get :change_status, on: :member
    end
  end

  root to: 'visitors#index'

  resources :investments do
    get :crop
  end
  # resources :companies do
    
  # end
  


  resources :terms


  resources :after_signup
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/crop" => "users#crop"
  resources :users do
    get :get_cities_by_country_code, on: :collection
    
    collection do
      get :filter_courses  
    end
  end

  resources :reports
  
  
  get "welcome" => "after_signup#welcome", as: :user_welcome
  get "location" => "after_signup#location", as: :user_location
  get "setup" => "after_signup#setup", as: :user_setup
  get "resume" => "after_signup#resume", as: :user_resume
  get '/faq', to: 'investments#faq'
  get '/privacy_policy', to: 'public#privacy_policy'

  end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :investments
  has_many :questionnaires, dependent: :destroy

  INDUSTRY = {
      "1" => "Airlines/Aviation",
"2" => "Alternative Dispute Resolution",
"3" => "Alternative Medicine",
"4" => "Animation",
"5" => "Apparel & Fashion",
"6" => "Architecture & Planning",
"7" => "Arts and Crafts",
"8" => "Automotive",
"9" => "viation & Aerospace",
"10" => "Banking",
"11" => "Biotechnology",
"12" => "Broadcast Media",
"13" => "Building Materials",
"14" => "Business Supplies and Equipment",
"15" => "Capital Markets",
"16" => "Chemicals",
"17" => "Civic & Social Organization",
"18" => "Civil Engineering",
"19" => "Commercial Real Estate",
"20" =>'Computer  & Network Security',
"21" => "Computer Games",
"22" => "Computer Hardware",
"23" => "Computer Networking",
"24" => "Computer Software",
"25" => "Construction",
"26" => "Consumer Electronics",
"27" => "Consumer Goods",
"28" => "Consumer Services",
"29" => "Cosmetics",
"30" => "Dairy",
"31" => "Defense & Space",
"32" => "Design",
"33" => "Education Management",
"34" => "E-Learning",
"35" => "Electrical/Electronic Manufacturing",
"36" => "Entertainment",
"37" => "Environmental Services",
"38" => "Events Services",
"39" => "Executive Office",
"40" => "Facilities Services",
"41" => "Financial Services",
"42" => "Fine Art",
"43" => "Fishery",
"44" => "Food & Beverages",
"45" => "Food Production",
"46" => "Fund-Raising",
"47" => "Furniture",
"48" => "Gambling & Casinos",
"49" => "Glass, Ceramics & Concrete",
"50" => "Government Administration",
"51" => "overnment Relations",
"52" => "Graphic Design",
"53" => "Health, Wellness and Fitness",
"54" => "Higher Education",
"55" => "Hospital & Health Care",
"56" => "Hospitality",
"57" => "Human Resources",
"58" => "Import and Export",
"59" => "Individual & Family Services",
"60" => "Industrial Automation",
"61" => "Information Services",
"62" =>"Information Technology and Services",
"63" =>"Insurance",
"64" =>"International Affairs",
"65" =>"International Trade and Development",
"66" =>"Internet",
"67" =>"Investment Banking",
"68" =>"Investment Management",
"69" =>"Judiciary",
"70" =>"Law Enforcement",
"71" =>"Law Practice",
"72" =>"Legal Services",
"73" =>"Legislative Office",
"74" =>"Leisure, Travel & Tourism",
"75" =>"Libraries",
"76" =>"Logistics and Supply Chain",
"77" =>"Luxury Goods & Jewelry",
"78" =>"Machinery",
"79" =>"Management Consulting",
"80" =>"Maritime",
"81" =>"Market Research",
"82" =>"Marketing and Advertising",
"83" =>"Mechanical or Industrial Engineering",
"84" =>"Media Production",
"85" =>"Medical Devices",
"86" =>"Medical Practice",
"87" =>"Mental Health Care",
"88" =>"Military",
"89" =>"Mining & Metals",
"90" =>"Motion Pictures and Film",
"91" =>"Museums and Institutions",
"92" =>"Music",
"93" =>"Nanotechnology",
"94" =>"Newspapers",
"95" =>"Non-Profit Organization Management",
"96" =>"Oil & Energy",
"97" =>"Online Media",
"98" =>"Outsourcing/Offshoring",
"99" =>"Package/Freight Delivery",
"100" =>"Packaging and Containers",
"101" =>"Paper & Forest Products",
"102" =>"Performing Arts",
"103" =>"Pharmaceuticals",
"104" =>"Philanthropy",
"105" =>"Photography",
"106" =>"Plastics",
"107" =>"Political Organization",
"108" =>"Primary/Secondary Education",
"109" =>"Printing",
"110" =>"Professional Training & Coaching",
"111" =>"Program Development",
"112" =>"Public Relations and Communications",
"113" =>"Public Safety",
"114" =>"Publishing",
"115" =>"Railroad Manufacture",
"116" =>"Ranching",
"117" =>"Real Estate",
"118" =>"Recreational Facilities and Services",
"119" =>"Religious Institutions",
"120" =>"Renewables & Environment",
"121" =>"Research",
"122" =>"Restaurants",
"123" =>"Retail",
"124" =>"Security and Investigations",
"125" =>"Semiconductors",
"126" =>"Shipbuilding",
"127" =>"Sports",
"128" =>"Staffing and Recruiting",
"129" =>"Supermarkets",
"130" =>"Telecommunications",
"131" =>"Textiles",
"132" =>"Think Tanks",
"133" =>"Tobacco",
"134" =>"Translation and Localization",
"135" =>"Transportation/Trucking/Railroad",
"136" =>"Utilities",
"137" =>"Venture Capital & Private Equity",
"138" =>"Veterinary",
"139" =>"Warehousing",
"140" =>"Wholesale",
"141" =>"Wine and Spirits",
"142" =>"Wireless",
"143" =>"Writing and Editing"
  }


  has_many :company_documents, :dependent => :destroy
  accepts_nested_attributes_for :company_documents, reject_if: :all_blank, allow_destroy: true

  has_many :sign_documents, as: :documentable, :dependent => :destroy
  accepts_nested_attributes_for :sign_documents, reject_if: :all_blank, allow_destroy: true

  has_many :company_photos, :dependent => :destroy
  accepts_nested_attributes_for :company_photos, reject_if: :all_blank, allow_destroy: true

  has_many :videos, :dependent => :destroy
  accepts_nested_attributes_for :videos, reject_if: :all_blank, allow_destroy: true
  belongs_to :user, foreign_key: :creator_id
  has_many :users, :class_name => "User", :through => :staffs, :source => :user
  has_many :staffs, :dependent => :destroy

  has_many :updates, as: :updateable, :dependent => :destroy
  accepts_nested_attributes_for :updates, allow_destroy: true, :reject_if => proc { |update| update['title'].blank? }

    attr_accessor :background_image_crop_x, :background_image_crop_y, :background_image_crop_w, :background_image_crop_h

  mount_uploader :logo, PhotoUploader
  mount_uploader :background_image, PhotoUploader
  crop_uploaded :background_image

  default_scope { order("name ASC") }

  after_create :send_company_created_email

  # validates_format_of :company_website, :with => URI::regexp(%w(http https))
  # validates_format_of :linkedin, :with => ( /(ftp|http|https):\/\/?(?:www\.)?linkedin.com(\w+:{0,1}\w*@)?(\S+)(:([0-9])+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/)
  # validates_format_of :facebook, :with => (/(https?:\/\/)?((w{3}\.)?)facebook.com\/.*/i) 
  # validates_format_of :twitter, :with => (/http(?:s)?:\/\/(?:www\.)?twitter\.com\/([a-zA-Z0-9_]+)/) 

  

  def staffs_with_role(role)
    self.users.send(role.to_sym)
  end

  private
  def send_company_created_email
    CompanyMailer.company_created_mail(self).deliver
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]  
  # caches_page :index
  # caches_action :index
  # GET /companies
  # GET /companies.json
  def index
    @grouped_companies = Company.all.group_by(&:geography)    
    @companies = params[:q] ? company_filteration(params[:q],params[:region]) : Company.all
    render layout: "browse"
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
     if  user_signed_in?
    else
      redirect_to root_path
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.sign_documents.new
  end

  # GET /companies/1/edit
  def edit
   if current_user && (@company.creator_id.eql?(current_user.id) || current_user.admin?)
    @company.sign_documents.new if !@company.sign_documents.present?
    else
      respond_to do |format|
        flash[:danger] = 'Unauthorized user!'
        format.html { redirect_to root_path }
      end
    end    
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        update_staffs
        docusign @company, params[:company][:sign_documents_attributes]
        # if company_params[:background_image].present?
        #   redirect_to company_crop_url(@company) and return
        # else
        image_cropping
          format.html { redirect_to @company, notice: 'Company was successfully created.' }
          format.json { render :show, status: :created, location: @company }
        # end
      else
        flash[:danger] = @company.errors.full_messages[0]
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update    
    respond_to do |format|
      if @company.update(company_params)
        image_cropping
        docusign @company, params[:company][:sign_documents_attributes]
        update_staffs
        # if company_params[:background_image].present?
        #   redirect_to company_crop_url(@company) and return
        # else
          format.html { redirect_to @company, notice: 'Company was successfully updated.' }
          format.json { render :show, status: :ok, location: @company }
        # end
      else
        flash[:danger] = @company.errors.full_messages[0]
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy    
    respond_to do |format|
      if current_user && (@company.creator_id.eql?(current_user.id) || current_user.admin?)
        @company.destroy
        format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
        format.json { head :no_content }
      else
        flash[:danger] = 'Unauthorized user!'
        format.html { redirect_to root_path }
      end
    end
  end

  def crop
    @company = Company.find(params[:company_id])
  end

  def get_cities_by_country_code; end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:staff_users, :name, :city, :country, :creator_id, :logo, :motto, :founded, :seeking, :raised, :tag, :industry, :amount_raised, :no_of_employees, :no_of_founders, :fundraising_amount, :company_website, :description, :readiness, :projections, :facebook, :twitter, :linkedin, :angellist, :country_of_incorporation, :growth_projections, :geography, :product_stage, :vision, :problem, :solution, :impact, :background_image, :background_image_crop_x, :background_image_crop_y, :background_image_crop_w, :background_image_crop_h, :company_documents_attributes => [:id, :document, :company_id, :_destroy], :sign_documents_attributes => [:id, :document, :company_id, :_destroy], :company_photos_attributes => [:id, :company_image, :_destroy], :videos_attributes => [:id, :title, :link, :description, :company_id, :_destroy], :user_ids => [], :updates_attributes => [:id, :title, :brief_description, :detailed_description, :_destroy])
    end

    def update_staffs
      if params["staff_users"].present?
        @company.staffs.destroy_all
        params["staff_users"].each do |role,user_ids|
          user_ids.reject!{|id| id.blank? }
          user_ids.each do |user_id|
            @company.staffs.create(:user_id => user_id, :role => role)
          end
        end
      end

    end


    def company_filteration(q,region)
      if region.eql?("All Regions") && q.blank?
        Company.all
      elsif region.eql?("All Regions") && !q.blank?
        Company.where("LOWER(name)=?", q.downcase)
      elsif q.blank?
        Company.where("geography=?", region)
      elsif !q.blank?
        Company.where("LOWER(name)=? AND geography=?", q.downcase, region)
      end
    end

    def image_cropping      
      if params[:crop].present?
        crop = JSON.parse(params[:crop])
        params[:company][:background_image_crop_x] = crop["left"]
        params[:company][:background_image_crop_y] = crop["top"]
        params[:company][:background_image_crop_w] = crop["width"]
        params[:company][:background_image_crop_h] = crop["height"]
        image = MiniMagick::Image.open(@company.background_image.url)        
        crop_params = "#{crop["width"]}x#{crop["height"]}+#{crop["left"]}+#{crop["top"]}"        
        image.crop(crop_params)
        image
        @company.background_image = image
        @company.update(company_params)
      end
    end
  
    def file_decode(base, filename)
      file = Tempfile.new([file_base_name(filename), file_extn_name(filename)])
      file.binmode
      file.write(Base64.decode64(base))
      file.close
      file
    end

    def file_base_name(file_name)
        File.basename(file_name, file_extn_name(file_name))
    end

    def file_extn_name(file_name)
        File.extname(file_name)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
	def cities f
		cities = f.object.country ? country_cities(f.object.country) : country_cities('AF')
		return cities
	end

	def country_cities code		
		country = Country.find_by_code(code)
		country.cities.order(:name).map { |city| [city.name, city.code] }		
	end

	def countries f
		Country.all.order(:name).map{|country| [country.name, country.code]}
	end

	def video_url link
		if link.include? "vimeo.com"
			"https://player.vimeo.com/video/#{link.split("vimeo.com/")[1]}?badge=0"
		else
			"https://www.youtube.com/embed/#{link.split("v=")[1]}"
		end
	end
	
end

app/views/companies/edit/_advisors.html.erb
<section id="nav-advisors">

  <h6>Notable Advisors</h6>
  <h2>[Advisor Selection here]</h2>

</section>

app/views/companies/edit/_header.html.erb
<%= header_bg_image_url = @company.background_image.present? ? @company.background_image.url : 'http://vestedworld.com/app/uploads/2016/03/3-1024x529.jpg' %>
<div class="profile-header-photo gradient reduced-height" style="background: url(<%= header_bg_image_url %>);">
  <div class="profile-header-photo-in">
    <div class="tbl-cell">
      <div class="info-block">
        <div class="container">
          <div class="row p-y-lg">
            <div class="col-lg-8 col-lg-offset-4">
              <%= f.submit "Update Company", class: "btn btn-block btn-danger sign-up" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to company_path(@company), type: "button", class: "change-cover m-a-lg" do %>
    <i class="font-icon font-icon-settings"></i>
    View Company
  <% end %>
</div><!--.profile-header-photo-->

app/views/companies/edit/_highlights.html.erb
<section id="highlights">
  <h6>HIGHLIGHTS</h6>

  <div class="row">
    <div class="col-md-6">
      <ul class="highlights">
        <li><%= @investment.highlights_1 %></li>
        <li><%= @investment.highlights_2 %></li>
        <li><%= @investment.highlights_3 %></li>
        <li><%= @investment.highlights_4 %></li>
        <li><%= @investment.highlights_5 %></li>
      </ul>
    </div>
    <div class="col-md-6">
      <ul class="highlights">
        <li><%= @investment.highlights_6 %></li>
        <li><%= @investment.highlights_7 %></li>
        <li><%= @investment.highlights_8 %></li>
        <li><%= @investment.highlights_9 %></li>
        <li><%= @investment.highlights_10 %></li>
      </ul>
    </div>
  </div>
</section>

app/views/companies/edit/_impact.html.erb
<section id="impact">
  <h6>economic, social and environmental impact</h6>
</section>

app/views/companies/edit/_investors.html.erb
<section id="nav-investors">
  <h6>VestedAngels and Select Investors</h6>
    <h2>[Investor Selection here]</h2>
</section>

app/views/companies/edit/_legal_notices.html.erb
<div class="" id="nav-notices">
  <p class="text-muted">
    <%=LegalNotice.first.try(:company_notice)%>
  </p>
</div>

app/views/companies/edit/_media.html.erb
<!-- Sign DOCUMENTS -->
<section id="nav-documents">
  <h2>Documents to Sign</h2>  
  <br/>
  <div id="company_sign_documents" class="bgcolor-light-grey p-a-lg brad-6">
    <div class="row">
      <div class="col-sm-12">
        <div id="company_sign_documents">
           <table class="table">
            <thead>
              <th>Document</th>
            </thead>
            <tbody>
              <%= f.fields_for :sign_documents do |sign_document_form| %>
                <%= render 'shared/sign_document_fields', f: sign_document_form %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>
<hr>
<!-- DOCUMENTS -->
<section id="nav-documents1">
  <h2>Documents</h2>
  <p>Please upload any corporate documents for your company below using the form. Any file format is allowable. Please keep files under 25MB in size to avoid issues with uploading. <b><u>Do not upload sensitive corporate documents.</u></b></p>
  <br/>
  <div id="company_documents" class="bgcolor-light-grey p-a-lg brad-6">
    <div class="row">
      <div class="col-sm-12">
        <div id="company_documents">
           <table class="table">
            <thead>
              <th>Title</th>
              <th>Documents</th>
              <th>File</th>
              <th>Actions</th>
            </thead>
            <tbody>
              <%= f.fields_for :company_documents do |company_document_form| %>
                <%= render 'companies/company_document_fields', f: company_document_form %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <hr/>
    <div class="links">
      <%= link_to_add_association f, :company_documents, class: "btn btn-primary btn-sm" do %>
        Add New
      <% end %>
    </div>
  </div>
</section>

<section id="nav-media">
  <h6><b>corporate media:</b> photos, documents, and videos</h6>

  <!-- PHOTOS -->
  <section class="p-a-0" id="photos">
    <h2>Photos</h2>
    <p>Please upload any corporate photos for your company below using the form. Any photo file format is allowable (.png, .jpg, .jpeg). Please keep files under 1GB in size to avoid issues with uploading. <b><u>Do not upload sensitive or innapropriate photos.</u></b></p>
    <br/>
    <div id="company_photos" class="bgcolor-light-grey p-a-lg brad-6">
      <div class="row">
        <div class="col-sm-12">
           <table class="table">
            <thead>
              <th>Title</th>
              <th>Documents</th>
              <th>File</th>
              <th>Actions</th>
            </thead>
            <tbody>
              <%= f.fields_for :company_photos do |company_photo_form| %>
                <%= render 'companies/company_photo_fields', f: company_photo_form %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <hr/>
      <div class="links">
        <%= link_to_add_association 'Add Photo', f, :company_photos, class: "btn btn-sm" %>
      </div>
    </div>
  </section>

  <!-- VIDEO -->
  <section class="p-a-0" id="videos">
    <h2>Videos</h2>
    <p>Please add any videos for your company below using the form. YouTube and Vimeo video are encouraged. Simply copy and paste the video link</p>
    <br/>
    <div id="company_video" class="">
      <div class="row">
        <div class="col-sm-12">
          <div id="videos">
            <%= f.fields_for :videos do |video_form| %>
              <%= render 'companies/video_fields', f: video_form %>
              <hr/>
            <% end %>
          </div>
        </div>
      </div>
      <hr/>
      <div class="links">
        <%= link_to_add_association 'Add Video', f, :videos, class: "btn btn-sm" %>
      </div>
    </div>
  </section>
</section>

app/views/companies/edit/_opportunity.html.erb
<section id="overview">
  <h6>the opportunity</h6>

  

  <div class="form-group">
    <label class="form-label">Our Vision <small>Copy and Paste Link</small></label>
    <%= f.text_area :vision, rows: "5", class: 'form-control', placeholder: "" %>
  </div>

  <br/>

  <div class="form-group">
    <label class="form-label">The Problem <small>Copy and Paste Link</small></label>
    <%= f.text_area :problem, rows: "5", class: 'form-control', placeholder: "" %>
  </div>

  <br/>

  <div class="form-group">
    <label class="form-label">Our Solution <small>Copy and Paste Link</small></label>
    <%= f.text_area :solution, rows: "5", class: 'form-control', placeholder: "" %>
  </div>

  <br/>

  <div class="form-group">
    <label class="form-label">Impact <small>Copy and Paste Link</small></label>
    <%= f.text_area :impact, rows: "5", class: 'form-control', placeholder: "" %>
  </div>
  

</section>

app/views/companies/edit/_overview.html.erb
<%=render 'companies/img_cropper'%>

<section class="nav-overview">
  <h4>1. Overview</h4>
  <p>
    Provide a brief description of the company.
  </p>
  <hr class="m-t-0"/>
  <div style="display:none;">
    <%= f.cropbox :background_image %> <br />
    <%= f.previewbox :background_image %>
  </div>
  <br/>


  <div class="form-group">
    <label class="form-label">Company Name<small> Use legal name, if available.</small></label>
    <%= f.text_field :name, class: 'form-control', placeholder: "Company Name",required: :true %> 
  </div>
  <br/>
  <div class="form-group">
    <label class="form-label">Brief Description <small>Quick description of what your copmany does.</small></label>
    <%= f.text_area :description, class: 'form-control', required: :true %> 
  </div>

  <br/>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="form-label">Industry</label>
         <%= f.collection_select :industry, Company::INDUSTRY.collect{|pt| [pt.flatten.first,pt.flatten.last] }, :last, :last ,{:prompt => 'Choose a category'}, {:required => true} %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="form-label">Stage </label>
        <%= f.select(:product_stage,[  ['Ideation', 'Ideation'], ['Pre-Validation', 'Pre-Validation'], ['Pre-MVP', 'Pre-MVP'], ['MVP', 'MVP'], ['Pre-PMF', 'Pre-PMF'], ['Product', 'Product'], ['Market Fit', 'Market Fit']],{:prompt => 'Choose a category'}, {:required => true})%>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="form-label">No. of Founders</label>
        <%= f.select(:no_of_founders,[  ['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6+', '6+'] ] ,{:prompt => 'Choose a category'}, {:required => true})%>
      </div>
    </div>
  </div>
  <br/>

  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <label class="form-label">Region <small></small></label>
        <%= f.select(:geography,[  ['Sub-Saharan Africa', 'Sub-Saharan Africa'], ['East Asia & Pacific', 'East Asia & Pacific'], ['Europe, Middle East, & North Africa', 'Europe, Middle East, & North Africa'], ['Latin America & the Caribbean', 'Latin America & the Caribbean'], ['South Asia', 'South Asia'], ['Global','Global']],{:prompt => 'Choose a category'}, {:required => true})%>
      </div>
    </div>
    <div class="col-md-7">
      <div class="form-group">
        <label class="form-label">Website <small>Copy and Paste Link</small></label>
        <%= f.text_field :company_website, class: 'form-control', placeholder: "http://ourcompany.com",required: :true, :id => "url" %>
        <div class="valid_url"></div>
      </div>
    </div>
  </div>
  <br/>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="form-label">Country</label>        
        <%= f.select(:country, countries(f), class: "select2 form-control",:prompt => 'Choose a Country')%>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="form-label">City</label>
        <div class="country_cities">
          <%= f.select(:city, cities(f), class: "select2 form-control",:prompt => 'Choose a City')%>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="form-label">No. of Employees</label>
        <%= f.select(:no_of_employees,[  ['1-10', '1-10'], ['10-50', '10-50'], ['50-100', '50-100']],{:prompt => 'Choose a category'}, {:required => true})%>
      </div>
    </div>
  </div>
  <hr/>

  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <label class="form-label">Profile Header Image</label>
        <%= f.file_field :background_image %>
      </div>
    </div>
    <div class="col-md-7">
      <div class="form-group">
        <label class="form-label">Company Logo Image</label>
        <%= f.file_field :logo %>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  $(document).ready(function(){
    $("#company_city, #company_country").attr("required", "true");
  })

  $("#url").keyup(function(){
  if((/^(http|https|ftp):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(this.value)) || this.value == "")  {
      $(".valid_url").hide().html("<b>Invalid URL</b>").css({ 'color': "red" });   
    }
    else{
      $(".valid_url").show().html("<b>Invalid URL</b>").css({ 'color': "red" });
    }
  });
</script>

app/views/companies/edit/_pitch.html.erb
<section id="nav-overview">
  <h6>the opportunity</h6>

  <h4 class="">Tell us about your company.</h4>

	<p id="nav-problem"> </p>
	<div class="form-group">
		<label class="form-label">Investment Readiness <small>Is your company ready for investment? Please explain why.</small></label>
		<%= f.text_area :readiness, class: 'form-control', placeholder: "", rows: "10" %>
	</div>

	<br/>
    <p id="nav-solution"> </p>
	<div class="form-group">
		<label class="form-label">Growth Projections <small>How do you envision your company growing over the next 3-24 months.</small></label>
		<%= f.text_area :growth_projections, class: 'form-control', placeholder: "", rows: "10" %>
	</div>
</section>