config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  # ActiveAdmin.routes(self)
#   namespace :admin do
#     resources :users
# resources :companies
# resources :company_documents
# resources :company_photos
# resources :faqs
# resources :investments
# resources :investment_documents
# resources :investment_photos
# resources :investment_videos
# resources :legals
# resources :questionnaires
# resources :reports
# resources :report_authors
# resources :report_categories
# resources :staffs
# resources :updates
# resources :user_documents
# resources :user_photos
# resources :user_videos
# resources :videos

  #   root to: "users#index"
  # end

  get 'public/index'

  get 'public/blog'

  get 'public/contact_us'

  get 'public/about'

  get 'public/team'

  get 'public/faq'

  get 'public/legal'

  get 'public/impact_investing'

  get 'pages/index'

  get 'pages/blog'

  get 'pages/contact_us'

  get 'pages/about'

  get 'pages/team'

  get 'pages/faq'

  get 'pages/legal'

  get 'pages/impact_investing'

  resources :legals
  resources :faqs


  # ActiveAdmin.routes(self)
  # resources :questionnaires, only: [:index] do
  #   get :change_status, on: :member
  # end

  resources :companies do
    get :crop
    get :get_cities_by_country_code, on: :collection
    resources :questionnaires do
      get :change_status, on: :member
    end
  end

  root to: 'visitors#index'

  resources :investments do
    get :crop
  end
  # resources :companies do
    
  # end
  


  resources :terms


  resources :after_signup
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/crop" => "users#crop"
  resources :users do
    get :get_cities_by_country_code, on: :collection
    
    collection do
      get :filter_courses  
    end
  end

  resources :reports
  
  
  get "welcome" => "after_signup#welcome", as: :user_welcome
  get "location" => "after_signup#location", as: :user_location
  get "setup" => "after_signup#setup", as: :user_setup
  get "resume" => "after_signup#resume", as: :user_resume
  get '/faq', to: 'investments#faq'
  get '/privacy_policy', to: 'public#privacy_policy'

  end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :investments
  has_many :questionnaires, dependent: :destroy

  INDUSTRY = {
      "1" => "Airlines/Aviation",
"2" => "Alternative Dispute Resolution",
"3" => "Alternative Medicine",
"4" => "Animation",
"5" => "Apparel & Fashion",
"6" => "Architecture & Planning",
"7" => "Arts and Crafts",
"8" => "Automotive",
"9" => "viation & Aerospace",
"10" => "Banking",
"11" => "Biotechnology",
"12" => "Broadcast Media",
"13" => "Building Materials",
"14" => "Business Supplies and Equipment",
"15" => "Capital Markets",
"16" => "Chemicals",
"17" => "Civic & Social Organization",
"18" => "Civil Engineering",
"19" => "Commercial Real Estate",
"20" =>'Computer  & Network Security',
"21" => "Computer Games",
"22" => "Computer Hardware",
"23" => "Computer Networking",
"24" => "Computer Software",
"25" => "Construction",
"26" => "Consumer Electronics",
"27" => "Consumer Goods",
"28" => "Consumer Services",
"29" => "Cosmetics",
"30" => "Dairy",
"31" => "Defense & Space",
"32" => "Design",
"33" => "Education Management",
"34" => "E-Learning",
"35" => "Electrical/Electronic Manufacturing",
"36" => "Entertainment",
"37" => "Environmental Services",
"38" => "Events Services",
"39" => "Executive Office",
"40" => "Facilities Services",
"41" => "Financial Services",
"42" => "Fine Art",
"43" => "Fishery",
"44" => "Food & Beverages",
"45" => "Food Production",
"46" => "Fund-Raising",
"47" => "Furniture",
"48" => "Gambling & Casinos",
"49" => "Glass, Ceramics & Concrete",
"50" => "Government Administration",
"51" => "overnment Relations",
"52" => "Graphic Design",
"53" => "Health, Wellness and Fitness",
"54" => "Higher Education",
"55" => "Hospital & Health Care",
"56" => "Hospitality",
"57" => "Human Resources",
"58" => "Import and Export",
"59" => "Individual & Family Services",
"60" => "Industrial Automation",
"61" => "Information Services",
"62" =>"Information Technology and Services",
"63" =>"Insurance",
"64" =>"International Affairs",
"65" =>"International Trade and Development",
"66" =>"Internet",
"67" =>"Investment Banking",
"68" =>"Investment Management",
"69" =>"Judiciary",
"70" =>"Law Enforcement",
"71" =>"Law Practice",
"72" =>"Legal Services",
"73" =>"Legislative Office",
"74" =>"Leisure, Travel & Tourism",
"75" =>"Libraries",
"76" =>"Logistics and Supply Chain",
"77" =>"Luxury Goods & Jewelry",
"78" =>"Machinery",
"79" =>"Management Consulting",
"80" =>"Maritime",
"81" =>"Market Research",
"82" =>"Marketing and Advertising",
"83" =>"Mechanical or Industrial Engineering",
"84" =>"Media Production",
"85" =>"Medical Devices",
"86" =>"Medical Practice",
"87" =>"Mental Health Care",
"88" =>"Military",
"89" =>"Mining & Metals",
"90" =>"Motion Pictures and Film",
"91" =>"Museums and Institutions",
"92" =>"Music",
"93" =>"Nanotechnology",
"94" =>"Newspapers",
"95" =>"Non-Profit Organization Management",
"96" =>"Oil & Energy",
"97" =>"Online Media",
"98" =>"Outsourcing/Offshoring",
"99" =>"Package/Freight Delivery",
"100" =>"Packaging and Containers",
"101" =>"Paper & Forest Products",
"102" =>"Performing Arts",
"103" =>"Pharmaceuticals",
"104" =>"Philanthropy",
"105" =>"Photography",
"106" =>"Plastics",
"107" =>"Political Organization",
"108" =>"Primary/Secondary Education",
"109" =>"Printing",
"110" =>"Professional Training & Coaching",
"111" =>"Program Development",
"112" =>"Public Relations and Communications",
"113" =>"Public Safety",
"114" =>"Publishing",
"115" =>"Railroad Manufacture",
"116" =>"Ranching",
"117" =>"Real Estate",
"118" =>"Recreational Facilities and Services",
"119" =>"Religious Institutions",
"120" =>"Renewables & Environment",
"121" =>"Research",
"122" =>"Restaurants",
"123" =>"Retail",
"124" =>"Security and Investigations",
"125" =>"Semiconductors",
"126" =>"Shipbuilding",
"127" =>"Sports",
"128" =>"Staffing and Recruiting",
"129" =>"Supermarkets",
"130" =>"Telecommunications",
"131" =>"Textiles",
"132" =>"Think Tanks",
"133" =>"Tobacco",
"134" =>"Translation and Localization",
"135" =>"Transportation/Trucking/Railroad",
"136" =>"Utilities",
"137" =>"Venture Capital & Private Equity",
"138" =>"Veterinary",
"139" =>"Warehousing",
"140" =>"Wholesale",
"141" =>"Wine and Spirits",
"142" =>"Wireless",
"143" =>"Writing and Editing"
  }


  has_many :company_documents, :dependent => :destroy
  accepts_nested_attributes_for :company_documents, reject_if: :all_blank, allow_destroy: true

  has_many :sign_documents, as: :documentable, :dependent => :destroy
  accepts_nested_attributes_for :sign_documents, reject_if: :all_blank, allow_destroy: true

  has_many :company_photos, :dependent => :destroy
  accepts_nested_attributes_for :company_photos, reject_if: :all_blank, allow_destroy: true

  has_many :videos, :dependent => :destroy
  accepts_nested_attributes_for :videos, reject_if: :all_blank, allow_destroy: true
  belongs_to :user, foreign_key: :creator_id
  has_many :users, :class_name => "User", :through => :staffs, :source => :user
  has_many :staffs, :dependent => :destroy

  has_many :updates, as: :updateable, :dependent => :destroy
  accepts_nested_attributes_for :updates, allow_destroy: true, :reject_if => proc { |update| update['title'].blank? }

    attr_accessor :background_image_crop_x, :background_image_crop_y, :background_image_crop_w, :background_image_crop_h

  mount_uploader :logo, PhotoUploader
  mount_uploader :background_image, PhotoUploader
  crop_uploaded :background_image

  default_scope { order("name ASC") }

  after_create :send_company_created_email

  # validates_format_of :company_website, :with => URI::regexp(%w(http https))
  # validates_format_of :linkedin, :with => ( /(ftp|http|https):\/\/?(?:www\.)?linkedin.com(\w+:{0,1}\w*@)?(\S+)(:([0-9])+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/)
  # validates_format_of :facebook, :with => (/(https?:\/\/)?((w{3}\.)?)facebook.com\/.*/i) 
  # validates_format_of :twitter, :with => (/http(?:s)?:\/\/(?:www\.)?twitter\.com\/([a-zA-Z0-9_]+)/) 

  

  def staffs_with_role(role)
    self.users.send(role.to_sym)
  end

  private
  def send_company_created_email
    CompanyMailer.company_created_mail(self).deliver
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]  
  # caches_page :index
  # caches_action :index
  # GET /companies
  # GET /companies.json
  def index
    @grouped_companies = Company.all.group_by(&:geography)    
    @companies = params[:q] ? company_filteration(params[:q],params[:region]) : Company.all
    render layout: "browse"
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
     if  user_signed_in?
    else
      redirect_to root_path
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.sign_documents.new
  end

  # GET /companies/1/edit
  def edit
   if current_user && (@company.creator_id.eql?(current_user.id) || current_user.admin?)
    @company.sign_documents.new if !@company.sign_documents.present?
    else
      respond_to do |format|
        flash[:danger] = 'Unauthorized user!'
        format.html { redirect_to root_path }
      end
    end    
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        update_staffs
        docusign @company, params[:company][:sign_documents_attributes]
        # if company_params[:background_image].present?
        #   redirect_to company_crop_url(@company) and return
        # else
        image_cropping
          format.html { redirect_to @company, notice: 'Company was successfully created.' }
          format.json { render :show, status: :created, location: @company }
        # end
      else
        flash[:danger] = @company.errors.full_messages[0]
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update    
    respond_to do |format|
      if @company.update(company_params)
        image_cropping
        docusign @company, params[:company][:sign_documents_attributes]
        update_staffs
        # if company_params[:background_image].present?
        #   redirect_to company_crop_url(@company) and return
        # else
          format.html { redirect_to @company, notice: 'Company was successfully updated.' }
          format.json { render :show, status: :ok, location: @company }
        # end
      else
        flash[:danger] = @company.errors.full_messages[0]
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy    
    respond_to do |format|
      if current_user && (@company.creator_id.eql?(current_user.id) || current_user.admin?)
        @company.destroy
        format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
        format.json { head :no_content }
      else
        flash[:danger] = 'Unauthorized user!'
        format.html { redirect_to root_path }
      end
    end
  end

  def crop
    @company = Company.find(params[:company_id])
  end

  def get_cities_by_country_code; end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:staff_users, :name, :city, :country, :creator_id, :logo, :motto, :founded, :seeking, :raised, :tag, :industry, :amount_raised, :no_of_employees, :no_of_founders, :fundraising_amount, :company_website, :description, :readiness, :projections, :facebook, :twitter, :linkedin, :angellist, :country_of_incorporation, :growth_projections, :geography, :product_stage, :vision, :problem, :solution, :impact, :background_image, :background_image_crop_x, :background_image_crop_y, :background_image_crop_w, :background_image_crop_h, :company_documents_attributes => [:id, :document, :company_id, :_destroy], :sign_documents_attributes => [:id, :document, :company_id, :_destroy], :company_photos_attributes => [:id, :company_image, :_destroy], :videos_attributes => [:id, :title, :link, :description, :company_id, :_destroy], :user_ids => [], :updates_attributes => [:id, :title, :brief_description, :detailed_description, :_destroy])
    end

    def update_staffs
      if params["staff_users"].present?
        @company.staffs.destroy_all
        params["staff_users"].each do |role,user_ids|
          user_ids.reject!{|id| id.blank? }
          user_ids.each do |user_id|
            @company.staffs.create(:user_id => user_id, :role => role)
          end
        end
      end

    end


    def company_filteration(q,region)
      if region.eql?("All Regions") && q.blank?
        Company.all
      elsif region.eql?("All Regions") && !q.blank?
        Company.where("LOWER(name)=?", q.downcase)
      elsif q.blank?
        Company.where("geography=?", region)
      elsif !q.blank?
        Company.where("LOWER(name)=? AND geography=?", q.downcase, region)
      end
    end

    def image_cropping      
      if params[:crop].present?
        crop = JSON.parse(params[:crop])
        params[:company][:background_image_crop_x] = crop["left"]
        params[:company][:background_image_crop_y] = crop["top"]
        params[:company][:background_image_crop_w] = crop["width"]
        params[:company][:background_image_crop_h] = crop["height"]
        image = MiniMagick::Image.open(@company.background_image.url)        
        crop_params = "#{crop["width"]}x#{crop["height"]}+#{crop["left"]}+#{crop["top"]}"        
        image.crop(crop_params)
        image
        @company.background_image = image
        @company.update(company_params)
      end
    end
  
    def file_decode(base, filename)
      file = Tempfile.new([file_base_name(filename), file_extn_name(filename)])
      file.binmode
      file.write(Base64.decode64(base))
      file.close
      file
    end

    def file_base_name(file_name)
        File.basename(file_name, file_extn_name(file_name))
    end

    def file_extn_name(file_name)
        File.extname(file_name)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
	def cities f
		cities = f.object.country ? country_cities(f.object.country) : country_cities('AF')
		return cities
	end

	def country_cities code		
		country = Country.find_by_code(code)
		country.cities.order(:name).map { |city| [city.name, city.code] }		
	end

	def countries f
		Country.all.order(:name).map{|country| [country.name, country.code]}
	end

	def video_url link
		if link.include? "vimeo.com"
			"https://player.vimeo.com/video/#{link.split("vimeo.com/")[1]}?badge=0"
		else
			"https://www.youtube.com/embed/#{link.split("v=")[1]}"
		end
	end
	
end

app/views/companies/_about.html.erb
<br/>
  
<div class="form-group row">
  <div class="col-md-4">
    <label class="form-label">No. of Founders</label>
    <h4><%= @company.no_of_founders %></h4>
  </div>
  <div class="col-md-4">
    <label class="form-label">No. of Employees</label>
    <h4><%= @company.no_of_employees %></h4>
  </div>
  <div class="col-md-4">
    <label class="form-label">Geographic Area</label>
     <h4><%= @company.geography %></h4>
  </div>
</div>
<div class="form-group row">
  <div class="col-md-4">
    <label class="form-label">Website</label>
    <h5><a href="<%= @company.company_website %>">Company Website</a></h5>
  </div>
  <div class="col-md-4">
    <label class="form-label">Country of Incorporation</label>
  </div>
</div>

<hr/>  


<h4 class="bold">Company Overview</h4>

<div class="form-group row">
  <div class="col-md-4">
    <label class="form-label">Industry</label>
    <h4><%= @company.industry %></h4>
  </div>
  <div class="col-md-4">
    <label class="form-label">Product Stage</label>
    <h4><%= @company.product_stage %></h4>
  </div>
  <div class="col-md-4">
    <label class="form-label">Technical Co-founder</label>
    
  </div>
</div>

<br/>

<div class="form-group row">
  <div class="col-md-3">
    <h5 class="text-primary">Brief Description<br/>
    <small class="text-muted">Elevator Pitch</small>
  </h5>
  </div>
  <div class="col-md-9">
    <p><%= @company.description %></p>
  </div>
</div>

<div class="form-group row">
  <div class="col-md-3">
    <h5 class="text-primary">Stage of Growth
      <small class="text-muted">Investment Readiness</small>
    </h5>
  </div>
  <div class="col-md-9">
    <p><%= @company.readiness %></p>
  </div>
</div>

<div class="form-group row">
  <div class="col-md-3">
    <h5 class="text-primary">
      Retun Projections<br/>
      <small class="text-muted">Return Expectations</small>
    </h5>
  </div>
  <div class="col-md-9">
    <p><%= @company.growth_projections %></p>
  </div>
</div>

<hr/>

<!--  <h4 class="bold">Pitch Deck & Financials</h4>

<div class="form-group row">
  <div class="col-md-9">
    Upload Powerpoint Deck and Financials
  </div>
  <input>
</div> -->

<!-- <hr> -->

<h4 class="bold">Social Profiles & Media</h4>
<div class="form-group row">
  <div class="col-md-4">
    <a href="<%= @company.linkedin %>" class="btn btn-primary btn-block">LinkedIn</a>
  </div>
  <div class="col-md-4">
    <a href="<%= @company.twitter %>" class="btn btn-warning btn-block">Twitter</a>
  </div>
  <div class="col-md-4">
    <a href="<%= @company.facebook %>" class="btn btn-info btn-block">Facebook</a>
  </div>
</div>

app/views/companies/_company.html.erb
<% @companies.each do |company| %>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
    <section class="box-typical box-shadow task-card task p-t-0 relative">      
      <div class="btn-group task-card-menu absolute p-r p-t">
        <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="text-warning font-icon-dots-vert-square"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to 'View', company, class: "dropdown-item" %>
          <% if current_user && (company.creator_id.eql?(current_user.id) || current_user.admin?) %>
            <%= link_to 'Edit', edit_company_path(company), class: "dropdown-item" %>
            <%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>            
          <% end %>    
        </div>
      </div>
      
      <div class="task-card-photo m-a-0">
        <%= link_to(company) do %>
          <% if company.logo.present? %>
            <%= image_tag company.logo.url %>
          <% else %>
            <%=image_tag("bg.jpeg")%>
          <% end %>
        <% end %>
        <div class="ribbon left-top"><%= company.industry %></div>        
      </div>
      <div class="task-card-in m-t">
        <h5 class="company"><%= link_to company.name, company %></h5>
        <small><%= company.geography %></small>
        <h6 class="tiny-header">SUMMARY</h6>
        <p class="small-descrip"><%= truncate(company.description, length: 120) %></p>
        <!-- 
        <h6 class="tiny-header">KEYWORDS</h6>
        <div class="task-card-tags">
          <a href="#" class="label label-default">
            <span class="text-white bold"><%= company.industry %></span>
          </a>
        </div> -->
      </div>
      <div class="task-card-footer">
        <div class="task-card-meta-item p-b">
          <% company.users.uniq[0..5].each do |user| %>
            <div class="avatar-preview avatar-preview-32">
              <%= image_tag(user.avatar.present? ? user.avatar.url : "avatar-1-128.png")%>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  </div>
<% end %>


<script>

  var data = {
    <% @grouped_companies.delete_if { |key, value| key.nil? }.each do |geography,_| %>
      "<%= geography.to_s.parameterize.underscore %>": <%= Company.where(:geography => geography).map(&:name).to_s.html_safe %>,
    <% end %>
  };

  typeof $.typeahead === 'function' && $.typeahead({
    input: ".js-typeahead-input",
    minLength: 1,
    maxItem: 15,
    order: "asc",
    hint: true,
    group: {
      template: "{{group}} beers!"
    },
    maxItemPerGroup: 5,
    backdrop: {
      "background-color": "#fff"
    },
    href: "/companies?q={{display}}&region="+$('input.select-region').val(),
    dropdownFilter: "All Regions",
    emptyTemplate: 'No result for "{{query}}"',
    source: {
      <% @grouped_companies.delete_if { |key, value| key.nil? }.each do |geography,_| %>
      "<%= geography %>": {
        data: data.<%= geography.to_s.parameterize.underscore %>
      },
      <% end %>
    },
    callback: {
      onClickAfter: function (node, a, item, event) {

        // href key gets added inside item from options.href configuration
        //alert(item.href);

      }
    },
    debug: false
  });

</script>

app/views/companies/_company_document_fields.html.erb
<tr class="nested-fields">
	<td><%=f.object.document.model[:document]%></td>
  <td><%= f.file_field :document %></td>
  <td>
    <%= link_to f.object.document.url do %>
      <%= image_tag("https://cdn4.iconfinder.com/data/icons/file-extensions-1/64/docs-128.png", class: "img-responsive", style: "height: 50px; width: auto;")%>
    <% end %>
  </td>
  <td>
    <%= link_to_remove_association f, class: "btn btn-sm btn-danger" do %>
      Delete
    <% end %>
  </td>
</tr>

app/views/companies/_company_photo_fields.html.erb
  <table width="100%">
    <tr class="nested-fields">
    	<td>File Name</td>
      <td><%= f.file_field :company_image %></td>
      <td>
        <%= link_to f.object.company_image.url, :target => "_blank" do %>
      		<%= image_tag(f.object.company_image.present? ? f.object.company_image.url : "file-img.png", style: "height: 50px; width: auto;") %>
      	<% end %>
      </td>
      <td>
        <%= link_to_remove_association f, class: "btn btn-sm btn-danger" do %>
          Delete
        <% end %>
      </td>
    </tr>
  </table>

app/views/companies/_form.html.erb
<%= render 'companies/edit/overview', f: f %>
<%= render 'companies/edit/pitch', f: f %>
<%#= render 'companies/edit/opportunity', f: f %>
<%#= render 'companies/edit/impact', f: f %>
<%= render 'companies/edit/team', f: f %>
<%= render 'companies/edit/media', f: f %>

<%= render 'companies/edit/social', f: f %>
<%= render 'companies/edit/update', f: f  %>

app/views/companies/_staff_fields.html.erb
<%= role = role || f.object.try(:user).try(:role) %>

<% raise f.object.role.inspect if role.nil? %>

<div class="nested-fields">
  <div>
    <%= f.collection_select :user_id, User.send(role.to_sym), :id, :email, :include_blank => "Select Investor", :class => 'form-control' %>
  </div>

  <%= link_to_remove_association "Remove", f, class: "btn btn-danger btn-sm" %>
</div>

app/views/companies/_video_fields.html.erb
<div class="nested-fields">

  <div class="form-group">
    <label class="form-label">Title <small>Descriptive video title</small></label>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>

  <br/>

  <div class="form-group">
    <label class="form-label">Video Link <small>Copy and paste YouTube or Vimeo share link.</small></label>
    <%= f.url_field :link, placeholder: "http://", :class => 'form-control' %>
  </div>

  <br/>

  <div class="form-group">
    <label class="form-label">Description <small>Please add a brief video description.</small></label>
    <%= f.text_area :description, :class => 'form-control' %>
  </div>

  <br/>

  <div class="form-group">
    <label class="form-label">Tags <small>Please add keyword tags for this video.</small></label>
    <%= f.text_area :tags, :class => 'form-control' %>
  </div>

  <%= link_to_remove_association "Remove", f, class: "btn btn-sm" %>
  
</div>

app/views/companies/edit.html.erb
<div class="bgcolor-white">

  <%= form_for(@company) do |f| %>

    <%= render 'companies/edit/header', f: f %>

    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <aside class="profile-side">
            <section class="box-typical box-transparent profile-side-user no-padding m-b-0">
              <div class="p-a-lg">
                <%= render 'companies/edit/nav/logo', f: f %>
              </div>
              <hr class="m-a-0"/>
              <div class="p-a" id ="sticker">
                <%= render 'companies/edit/nav/links' %>
              </div>
            </section>
          </aside><!--.profile-side-->
        </div>

        <div class="col-lg-8 show">
          <%=link_to "Questionnaire", company_questionnaires_path(@company)%>
          <%= render 'form', f: f %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%=render 'shared/investment_terms'%>
<style type="text/css">
.stick {
  position:fixed;
  top:70px !important;
  border: 1px solid #d8e2e7;
}
.profile-side {
  margin: -245px 0 21px 20px;
}
</style>
<script type="text/javascript">
  $(document).ready(function() {
    var s = $("#sticker");
    var pos = s.position();                    
    $(window).scroll(function() {
        var windowpos = $(window).scrollTop();
        if (windowpos >= pos.top) {
            s.addClass("stick");
        } else {
            s.removeClass("stick"); 
        }
    });
});
</script>

app/views/companies/get_cities_by_country_code.js.erb
$('.country_cities').html("<%=j render 'shared/company_cities', con: params[:code]%>");

app/views/companies/show.html.erb
<div class="bgcolor-white">
  <%= render 'companies/show/header' %>
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <aside class="profile-side">
          <section class="box-typical box-transparent profile-side-user no-padding m-b-0">
            <div class="p-a-lg">
              <%= render 'companies/show/nav/logo' %>
            </div>
            <hr class="m-a-0"/>
            <div class="p-a" id ="sticker">
              <%= render 'companies/show/nav/links' %>
            </div>
          </section>
        </aside><!--.profile-side-->
      </div>

      <div class="col-lg-8 show">
        <%=link_to "Questionnaire", company_questionnaires_path(@company)%>
        <%= render 'companies/show/legal_notices' %>
        <%= render 'companies/show/overview' %>
        <%= render 'companies/show/opportunity' %>
        <%#= render 'companies/show/impact' %>
        <%= render :partial => 'companies/show/team', :locals => {:company => @company} %>
        <%= render :partial => 'companies/show/advisors', :locals => {:company => @company} %>
        <%= render :partial => 'companies/show/investors', :locals => {:company => @company} %>
        <%= render 'companies/show/media' %>
        <% if company_updates_showable?(current_user,@company) %>
          <%= render 'companies/show/updates' %>
        <% end %>
      </div>
    </div><!--.row-->
  </div><!--.container-fluid-->
</div><!--.page-content-->
<%=render 'shared/investment_terms'%>
<%#= link_to 'Edit', edit_company_path(@company) %> |
<%#= link_to 'Back', companies_path %>
<style type="text/css">

.stick {
  position:fixed;
  top:70px !important;
  border: 1px solid #d8e2e7;
}
.profile-side {
  margin: -245px 0 21px 20px;
}
</style>
<script type="text/javascript">
  $(document).ready(function() {
    var s = $("#sticker");
    var pos = s.position();                    
    $(window).scroll(function() {
        var windowpos = $(window).scrollTop();
        if (windowpos >= pos.top) {
            s.addClass("stick");
        } else {
            s.removeClass("stick"); 
        }
    });
});
</script>